### ISSUE TITLE
Extension can't be installed in Playnite 8

### ISSUE THREAD

**Issue by darklinkpower** [tomblind/playnite-categorysync#1]
Playnite 8 requires an `Id` property in extension manifests or will refuse to install

https://playnite.link/docs/playnite8/changelog.html
https://playnite.link/docs/playnite8/tutorials/extensionsManifest.html

![imagen](https://user-images.githubusercontent.com/1389286/96120923-e7281d00-0eb4-11eb-9a25-11796d1bff47.png)

**Comment by tomblind** [comment]
Fixed by 117f61ad6bdd5c58bef7a02467f8e86741262062
Available as [release v0.1.2](https://github.com/tomblind/playnite-categorysync/releases)
